package com.marcin.panklex

import com.badlogic.gdx.assets.AssetManager
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.graphics.g2d.TextureRegion
import com.badlogic.gdx.maps.tiled.tiles.StaticTiledMapTile

class KlexTiles(assetManager : AssetManager)
{
    // action

    val pickaxe = TextureRegion(assetManager.get<Texture>("graphics/actions/pickaxe.png")).split(32, 32)
    val pickaxe_unsel = StaticTiledMapTile(pickaxe[0][0])
    val pickaxe_sel = StaticTiledMapTile(pickaxe[0][1])
    val pickaxe_tile = StaticTiledMapTile(pickaxe[0][2])

    val bomb = TextureRegion(assetManager.get<Texture>("graphics/actions/bomb.png")).split(32, 32)
    val bomb_unsel = StaticTiledMapTile(bomb[0][0])
    val bomb_sel = StaticTiledMapTile(bomb[0][1])
    val bomb_tile = StaticTiledMapTile(bomb[0][2])

    val coin = TextureRegion(assetManager.get<Texture>("graphics/actions/coin.png")).split(32, 32)
    val coin_unsel = StaticTiledMapTile(coin[0][0])
    val coin_sel = StaticTiledMapTile(coin[0][1])
    val coin_tile = StaticTiledMapTile(coin[0][2])

    val cell = TextureRegion(assetManager.get<Texture>("graphics/actions/cell.png")).split(32, 32)
    val cell_unsel = StaticTiledMapTile(cell[0][0])
    val cell_sel = StaticTiledMapTile(cell[0][1])
    val cell_tile = StaticTiledMapTile(cell[0][2])

    val hand = TextureRegion(assetManager.get<Texture>("graphics/actions/hand.png")).split(32, 32)
    val hand_unsel = StaticTiledMapTile(hand[0][0])
    val hand_sel = StaticTiledMapTile(hand[0][1])
    val hand_tile = StaticTiledMapTile(hand[0][2])

    val walk = TextureRegion(assetManager.get<Texture>("graphics/actions/walk.png")).split(32, 32)
    val walk_unsel = StaticTiledMapTile(walk[0][0])
    val walk_sel = StaticTiledMapTile(walk[0][1])
    val walk_tile = StaticTiledMapTile(walk[0][2])

    val cancel = StaticTiledMapTile(TextureRegion(assetManager.get<Texture>("graphics/actions/cancel.png")))

    // entities

    val player = StaticTiledMapTile(TextureRegion(assetManager.get<Texture>("graphics/entities/player.png")))
    val container = StaticTiledMapTile(TextureRegion(assetManager.get<Texture>("graphics/entities/container.png")))
    val elevator = StaticTiledMapTile(TextureRegion(assetManager.get<Texture>("graphics/entities/elevator.png")))
    val flag = StaticTiledMapTile(TextureRegion(assetManager.get<Texture>("graphics/entities/flag.png")))

    val vendingMachine = TextureRegion(assetManager.get<Texture>("graphics/entities/vendingMachine.png")).split(32, 64)
    val vendingMachine_unbroken = StaticTiledMapTile(vendingMachine[0][0])
    val vendingMachine_broken = StaticTiledMapTile(vendingMachine[0][1])

    val teleporter = TextureRegion(assetManager.get<Texture>("graphics/entities/teleporter.png")).split(32, 64)
    val teleporter_unpow_unpow = StaticTiledMapTile(teleporter[0][0])
    val teleporter_pow_unpow = StaticTiledMapTile(teleporter[0][1])
    val teleporter_unpow_pow = StaticTiledMapTile(teleporter[0][2])
    val teleporter_pow_pow = StaticTiledMapTile(teleporter[0][3])

    val stairs = TextureRegion(assetManager.get<Texture>("graphics/entities/stairs.png")).split(32, 64)
    val stairs_b_r = StaticTiledMapTile(stairs[0][0])
    val stairs_b_l = StaticTiledMapTile(TextureRegion(stairs[0][0]).apply { flip(true, false) })
    val stairs_b_d = StaticTiledMapTile(stairs[0][1])
    val stairs_b_u = StaticTiledMapTile(stairs[0][2])
    val stairs_a_r = StaticTiledMapTile(stairs[0][3])
    val stairs_a_l = StaticTiledMapTile(TextureRegion(stairs[0][3]).apply { flip(true, false) })
    val stairs_a_u = StaticTiledMapTile(stairs[0][4])
    val stairs_a_d = StaticTiledMapTile(stairs[0][5])

    val poweredGate = TextureRegion(assetManager.get<Texture>("graphics/entities/poweredGate.png")).split(32, 64)
    val poweredGate_part_unp = StaticTiledMapTile(poweredGate[0][0])
    val poweredGate_part_pow = StaticTiledMapTile(poweredGate[0][1])
    val poweredGate_gate_hor_l = StaticTiledMapTile(poweredGate[0][2])
    val poweredGate_gate_hor_r = StaticTiledMapTile(TextureRegion(poweredGate[0][2]).apply { flip(true, false) })
    val poweredGate_gate_hor_l_r = StaticTiledMapTile(poweredGate[0][3])
    val poweredGate_gate_ver_u_d = StaticTiledMapTile(poweredGate[0][4])
    val poweredGate_gate_ver_d = StaticTiledMapTile(poweredGate[0][5])
    val poweredGate_gate_ver_u = StaticTiledMapTile(poweredGate[0][6])

    // special

    val special = TextureRegion(assetManager.get<Texture>("graphics/blocks/special.png")).split(32, 32)
    val hole = StaticTiledMapTile(special[0][0])
    val cover_half = StaticTiledMapTile(special[0][1])
    val cover_all = StaticTiledMapTile(special[0][2])
    val empty = StaticTiledMapTile(special[0][3])

    // example

    val example = TextureRegion(assetManager.get<Texture>("graphics/blocks/example.png")).split(32, 32)

    val exampleBase_ul = StaticTiledMapTile(example[0][0])
    val exampleBase_ur = StaticTiledMapTile(example[0][1])
    val exampleBase_dr = StaticTiledMapTile(example[1][1])
    val exampleBase_dl = StaticTiledMapTile(example[1][0])
    val exampleBase_ul_ur = StaticTiledMapTile(example[0][2])
    val exampleBase_ur_dr = StaticTiledMapTile(example[0][3])
    val exampleBase_dr_dl = StaticTiledMapTile(example[1][3])
    val exampleBase_ul_dl = StaticTiledMapTile(example[1][2])
    val exampleBase_ul_ur_dr = StaticTiledMapTile(example[0][4])
    val exampleBase_ur_dr_dl = StaticTiledMapTile(example[0][5])
    val exampleBase_ul_dr_dl = StaticTiledMapTile(example[1][5])
    val exampleBase_ul_ur_dl = StaticTiledMapTile(example[1][4])
    val exampleBase_ul_u_ur_r_dr = StaticTiledMapTile(example[0][6])
    val exampleBase_ur_r_dr_d_dl = StaticTiledMapTile(example[0][7])
    val exampleBase_ul_dr_d_dl_l = StaticTiledMapTile(example[1][7])
    val exampleBase_ul_u_ur_dl_l = StaticTiledMapTile(example[1][6])
    val exampleBase_ul_u_ur_r_dr_dl = StaticTiledMapTile(example[0][8])
    val exampleBase_ul_ur_r_dr_d_dl = StaticTiledMapTile(example[0][9])
    val exampleBase_ul_ur_dr_d_dl_l = StaticTiledMapTile(example[1][9])
    val exampleBase_ul_u_ur_dr_dl_l = StaticTiledMapTile(example[1][8])
    val exampleBase_ul_u_ur_r_dr_d_dl = StaticTiledMapTile(example[0][10])
    val exampleBase_ul_ur_r_dr_d_dl_l = StaticTiledMapTile(example[0][11])
    val exampleBase_ul_u_ur_dr_d_dl_l = StaticTiledMapTile(example[1][11])
    val exampleBase_ul_u_ur_r_dr_dl_l = StaticTiledMapTile(example[1][10])
    val exampleBase_ul_u_ur = StaticTiledMapTile(example[2][0])
    val exampleBase_ur_r_dr = StaticTiledMapTile(example[2][1])
    val exampleBase_dr_d_dl = StaticTiledMapTile(example[3][1])
    val exampleBase_ul_dl_l = StaticTiledMapTile(example[3][0])
    val exampleBase_ul_u_ur_dl = StaticTiledMapTile(example[2][2])
    val exampleBase_ul_ur_r_dr = StaticTiledMapTile(example[2][3])
    val exampleBase_ur_dr_d_dl = StaticTiledMapTile(example[3][3])
    val exampleBase_ul_dr_dl_l = StaticTiledMapTile(example[3][2])
    val exampleBase_ul_u_ur_dr = StaticTiledMapTile(example[2][4])
    val exampleBase_ur_r_dr_dl = StaticTiledMapTile(example[2][5])
    val exampleBase_ul_dr_d_dl = StaticTiledMapTile(example[3][5])
    val exampleBase_ul_ur_dl_l = StaticTiledMapTile(example[3][4])
    val exampleBase_ul_u_ur_dr_dl = StaticTiledMapTile(example[2][6])
    val exampleBase_ul_ur_r_dr_dl = StaticTiledMapTile(example[2][7])
    val exampleBase_ul_ur_dr_d_dl = StaticTiledMapTile(example[3][7])
    val exampleBase_ul_ur_dr_dl_l = StaticTiledMapTile(example[3][6])
    val exampleBase_ul_u_ur_dr_d_dl = StaticTiledMapTile(example[2][8])
    val exampleBase_ul_ur_r_dr_dl_l = StaticTiledMapTile(example[3][8])
    val exampleBase_ul_dr = StaticTiledMapTile(example[2][9])
    val exampleBase_ur_dl = StaticTiledMapTile(example[3][9])
    val exampleBase_ul_ur_dr_dl = StaticTiledMapTile(example[2][10])
    val exampleBase_ul_u_ur_r_dr_d_dl_l = StaticTiledMapTile(example[3][10])
    val exampleBase_none = StaticTiledMapTile(example[2][11])

    val exampleWall_l_m_r = StaticTiledMapTile(example[4][0])
    val exampleWall_l_m = StaticTiledMapTile(example[4][1])
    val exampleWall_m = StaticTiledMapTile(example[4][2])
    val exampleWall_m_r = StaticTiledMapTile(example[4][3])

    val exampleHole_l_m_r = StaticTiledMapTile(example[4][4])
    val exampleHole_l_m = StaticTiledMapTile(example[4][5])
    val exampleHole_m = StaticTiledMapTile(example[4][6])
    val exampleHole_m_r = StaticTiledMapTile(example[4][7])

    // undamaged stone

    val undamagedStone = TextureRegion(assetManager.get<Texture>("graphics/blocks/undamagedStone.png")).split(32, 32)

    val undamagedStoneBase_ul = StaticTiledMapTile(undamagedStone[0][0])
    val undamagedStoneBase_ur = StaticTiledMapTile(undamagedStone[0][1])
    val undamagedStoneBase_dr = StaticTiledMapTile(undamagedStone[1][1])
    val undamagedStoneBase_dl = StaticTiledMapTile(undamagedStone[1][0])
    val undamagedStoneBase_ul_ur = StaticTiledMapTile(undamagedStone[0][2])
    val undamagedStoneBase_ur_dr = StaticTiledMapTile(undamagedStone[0][3])
    val undamagedStoneBase_dr_dl = StaticTiledMapTile(undamagedStone[1][3])
    val undamagedStoneBase_ul_dl = StaticTiledMapTile(undamagedStone[1][2])
    val undamagedStoneBase_ul_ur_dr = StaticTiledMapTile(undamagedStone[0][4])
    val undamagedStoneBase_ur_dr_dl = StaticTiledMapTile(undamagedStone[0][5])
    val undamagedStoneBase_ul_dr_dl = StaticTiledMapTile(undamagedStone[1][5])
    val undamagedStoneBase_ul_ur_dl = StaticTiledMapTile(undamagedStone[1][4])
    val undamagedStoneBase_ul_u_ur_r_dr = StaticTiledMapTile(undamagedStone[0][6])
    val undamagedStoneBase_ur_r_dr_d_dl = StaticTiledMapTile(undamagedStone[0][7])
    val undamagedStoneBase_ul_dr_d_dl_l = StaticTiledMapTile(undamagedStone[1][7])
    val undamagedStoneBase_ul_u_ur_dl_l = StaticTiledMapTile(undamagedStone[1][6])
    val undamagedStoneBase_ul_u_ur_r_dr_dl = StaticTiledMapTile(undamagedStone[0][8])
    val undamagedStoneBase_ul_ur_r_dr_d_dl = StaticTiledMapTile(undamagedStone[0][9])
    val undamagedStoneBase_ul_ur_dr_d_dl_l = StaticTiledMapTile(undamagedStone[1][9])
    val undamagedStoneBase_ul_u_ur_dr_dl_l = StaticTiledMapTile(undamagedStone[1][8])
    val undamagedStoneBase_ul_u_ur_r_dr_d_dl = StaticTiledMapTile(undamagedStone[0][10])
    val undamagedStoneBase_ul_ur_r_dr_d_dl_l = StaticTiledMapTile(undamagedStone[0][11])
    val undamagedStoneBase_ul_u_ur_dr_d_dl_l = StaticTiledMapTile(undamagedStone[1][11])
    val undamagedStoneBase_ul_u_ur_r_dr_dl_l = StaticTiledMapTile(undamagedStone[1][10])
    val undamagedStoneBase_ul_u_ur = StaticTiledMapTile(undamagedStone[2][0])
    val undamagedStoneBase_ur_r_dr = StaticTiledMapTile(undamagedStone[2][1])
    val undamagedStoneBase_dr_d_dl = StaticTiledMapTile(undamagedStone[3][1])
    val undamagedStoneBase_ul_dl_l = StaticTiledMapTile(undamagedStone[3][0])
    val undamagedStoneBase_ul_u_ur_dl = StaticTiledMapTile(undamagedStone[2][2])
    val undamagedStoneBase_ul_ur_r_dr = StaticTiledMapTile(undamagedStone[2][3])
    val undamagedStoneBase_ur_dr_d_dl = StaticTiledMapTile(undamagedStone[3][3])
    val undamagedStoneBase_ul_dr_dl_l = StaticTiledMapTile(undamagedStone[3][2])
    val undamagedStoneBase_ul_u_ur_dr = StaticTiledMapTile(undamagedStone[2][4])
    val undamagedStoneBase_ur_r_dr_dl = StaticTiledMapTile(undamagedStone[2][5])
    val undamagedStoneBase_ul_dr_d_dl = StaticTiledMapTile(undamagedStone[3][5])
    val undamagedStoneBase_ul_ur_dl_l = StaticTiledMapTile(undamagedStone[3][4])
    val undamagedStoneBase_ul_u_ur_dr_dl = StaticTiledMapTile(undamagedStone[2][6])
    val undamagedStoneBase_ul_ur_r_dr_dl = StaticTiledMapTile(undamagedStone[2][7])
    val undamagedStoneBase_ul_ur_dr_d_dl = StaticTiledMapTile(undamagedStone[3][7])
    val undamagedStoneBase_ul_ur_dr_dl_l = StaticTiledMapTile(undamagedStone[3][6])
    val undamagedStoneBase_ul_u_ur_dr_d_dl = StaticTiledMapTile(undamagedStone[2][8])
    val undamagedStoneBase_ul_ur_r_dr_dl_l = StaticTiledMapTile(undamagedStone[3][8])
    val undamagedStoneBase_ul_dr = StaticTiledMapTile(undamagedStone[2][9])
    val undamagedStoneBase_ur_dl = StaticTiledMapTile(undamagedStone[3][9])
    val undamagedStoneBase_ul_ur_dr_dl = StaticTiledMapTile(undamagedStone[2][10])
    val undamagedStoneBase_ul_u_ur_r_dr_d_dl_l = StaticTiledMapTile(undamagedStone[3][10])
    val undamagedStoneBase_none = StaticTiledMapTile(undamagedStone[2][11])

    val undamagedStoneWall_l_m_r = StaticTiledMapTile(undamagedStone[4][0])
    val undamagedStoneWall_l_m = StaticTiledMapTile(undamagedStone[4][1])
    val undamagedStoneWall_m = StaticTiledMapTile(undamagedStone[4][2])
    val undamagedStoneWall_m_r = StaticTiledMapTile(undamagedStone[4][3])

    val undamagedStoneHole_l_m_r = StaticTiledMapTile(undamagedStone[4][4])
    val undamagedStoneHole_l_m = StaticTiledMapTile(undamagedStone[4][5])
    val undamagedStoneHole_m = StaticTiledMapTile(undamagedStone[4][6])
    val undamagedStoneHole_m_r = StaticTiledMapTile(undamagedStone[4][7])

    // damaged stone

    val damagedStone = TextureRegion(assetManager.get<Texture>("graphics/blocks/damagedStone.png")).split(32, 32)

    val damagedStoneBase_ul = StaticTiledMapTile(damagedStone[0][0])
    val damagedStoneBase_ur = StaticTiledMapTile(damagedStone[0][1])
    val damagedStoneBase_dr = StaticTiledMapTile(damagedStone[1][1])
    val damagedStoneBase_dl = StaticTiledMapTile(damagedStone[1][0])
    val damagedStoneBase_ul_ur = StaticTiledMapTile(damagedStone[0][2])
    val damagedStoneBase_ur_dr = StaticTiledMapTile(damagedStone[0][3])
    val damagedStoneBase_dr_dl = StaticTiledMapTile(damagedStone[1][3])
    val damagedStoneBase_ul_dl = StaticTiledMapTile(damagedStone[1][2])
    val damagedStoneBase_ul_ur_dr = StaticTiledMapTile(damagedStone[0][4])
    val damagedStoneBase_ur_dr_dl = StaticTiledMapTile(damagedStone[0][5])
    val damagedStoneBase_ul_dr_dl = StaticTiledMapTile(damagedStone[1][5])
    val damagedStoneBase_ul_ur_dl = StaticTiledMapTile(damagedStone[1][4])
    val damagedStoneBase_ul_u_ur_r_dr = StaticTiledMapTile(damagedStone[0][6])
    val damagedStoneBase_ur_r_dr_d_dl = StaticTiledMapTile(damagedStone[0][7])
    val damagedStoneBase_ul_dr_d_dl_l = StaticTiledMapTile(damagedStone[1][7])
    val damagedStoneBase_ul_u_ur_dl_l = StaticTiledMapTile(damagedStone[1][6])
    val damagedStoneBase_ul_u_ur_r_dr_dl = StaticTiledMapTile(damagedStone[0][8])
    val damagedStoneBase_ul_ur_r_dr_d_dl = StaticTiledMapTile(damagedStone[0][9])
    val damagedStoneBase_ul_ur_dr_d_dl_l = StaticTiledMapTile(damagedStone[1][9])
    val damagedStoneBase_ul_u_ur_dr_dl_l = StaticTiledMapTile(damagedStone[1][8])
    val damagedStoneBase_ul_u_ur_r_dr_d_dl = StaticTiledMapTile(damagedStone[0][10])
    val damagedStoneBase_ul_ur_r_dr_d_dl_l = StaticTiledMapTile(damagedStone[0][11])
    val damagedStoneBase_ul_u_ur_dr_d_dl_l = StaticTiledMapTile(damagedStone[1][11])
    val damagedStoneBase_ul_u_ur_r_dr_dl_l = StaticTiledMapTile(damagedStone[1][10])
    val damagedStoneBase_ul_u_ur = StaticTiledMapTile(damagedStone[2][0])
    val damagedStoneBase_ur_r_dr = StaticTiledMapTile(damagedStone[2][1])
    val damagedStoneBase_dr_d_dl = StaticTiledMapTile(damagedStone[3][1])
    val damagedStoneBase_ul_dl_l = StaticTiledMapTile(damagedStone[3][0])
    val damagedStoneBase_ul_u_ur_dl = StaticTiledMapTile(damagedStone[2][2])
    val damagedStoneBase_ul_ur_r_dr = StaticTiledMapTile(damagedStone[2][3])
    val damagedStoneBase_ur_dr_d_dl = StaticTiledMapTile(damagedStone[3][3])
    val damagedStoneBase_ul_dr_dl_l = StaticTiledMapTile(damagedStone[3][2])
    val damagedStoneBase_ul_u_ur_dr = StaticTiledMapTile(damagedStone[2][4])
    val damagedStoneBase_ur_r_dr_dl = StaticTiledMapTile(damagedStone[2][5])
    val damagedStoneBase_ul_dr_d_dl = StaticTiledMapTile(damagedStone[3][5])
    val damagedStoneBase_ul_ur_dl_l = StaticTiledMapTile(damagedStone[3][4])
    val damagedStoneBase_ul_u_ur_dr_dl = StaticTiledMapTile(damagedStone[2][6])
    val damagedStoneBase_ul_ur_r_dr_dl = StaticTiledMapTile(damagedStone[2][7])
    val damagedStoneBase_ul_ur_dr_d_dl = StaticTiledMapTile(damagedStone[3][7])
    val damagedStoneBase_ul_ur_dr_dl_l = StaticTiledMapTile(damagedStone[3][6])
    val damagedStoneBase_ul_u_ur_dr_d_dl = StaticTiledMapTile(damagedStone[2][8])
    val damagedStoneBase_ul_ur_r_dr_dl_l = StaticTiledMapTile(damagedStone[3][8])
    val damagedStoneBase_ul_dr = StaticTiledMapTile(damagedStone[2][9])
    val damagedStoneBase_ur_dl = StaticTiledMapTile(damagedStone[3][9])
    val damagedStoneBase_ul_ur_dr_dl = StaticTiledMapTile(damagedStone[2][10])
    val damagedStoneBase_ul_u_ur_r_dr_d_dl_l = StaticTiledMapTile(damagedStone[3][10])
    val damagedStoneBase_none = StaticTiledMapTile(damagedStone[2][11])

    val damagedStoneWall_l_m_r = StaticTiledMapTile(damagedStone[4][0])
    val damagedStoneWall_l_m = StaticTiledMapTile(damagedStone[4][1])
    val damagedStoneWall_m = StaticTiledMapTile(damagedStone[4][2])
    val damagedStoneWall_m_r = StaticTiledMapTile(damagedStone[4][3])

    val damagedStoneHole_l_m_r = StaticTiledMapTile(damagedStone[4][4])
    val damagedStoneHole_l_m = StaticTiledMapTile(damagedStone[4][5])
    val damagedStoneHole_m = StaticTiledMapTile(damagedStone[4][6])
    val damagedStoneHole_m_r = StaticTiledMapTile(damagedStone[4][7])

    // brick

    val brick = TextureRegion(assetManager.get<Texture>("graphics/blocks/brick.png")).split(32, 32)

    val brickBase_ul = StaticTiledMapTile(brick[0][0])
    val brickBase_ur = StaticTiledMapTile(brick[0][1])
    val brickBase_dr = StaticTiledMapTile(brick[1][1])
    val brickBase_dl = StaticTiledMapTile(brick[1][0])
    val brickBase_ul_ur = StaticTiledMapTile(brick[0][2])
    val brickBase_ur_dr = StaticTiledMapTile(brick[0][3])
    val brickBase_dr_dl = StaticTiledMapTile(brick[1][3])
    val brickBase_ul_dl = StaticTiledMapTile(brick[1][2])
    val brickBase_ul_ur_dr = StaticTiledMapTile(brick[0][4])
    val brickBase_ur_dr_dl = StaticTiledMapTile(brick[0][5])
    val brickBase_ul_dr_dl = StaticTiledMapTile(brick[1][5])
    val brickBase_ul_ur_dl = StaticTiledMapTile(brick[1][4])
    val brickBase_ul_u_ur_r_dr = StaticTiledMapTile(brick[0][6])
    val brickBase_ur_r_dr_d_dl = StaticTiledMapTile(brick[0][7])
    val brickBase_ul_dr_d_dl_l = StaticTiledMapTile(brick[1][7])
    val brickBase_ul_u_ur_dl_l = StaticTiledMapTile(brick[1][6])
    val brickBase_ul_u_ur_r_dr_dl = StaticTiledMapTile(brick[0][8])
    val brickBase_ul_ur_r_dr_d_dl = StaticTiledMapTile(brick[0][9])
    val brickBase_ul_ur_dr_d_dl_l = StaticTiledMapTile(brick[1][9])
    val brickBase_ul_u_ur_dr_dl_l = StaticTiledMapTile(brick[1][8])
    val brickBase_ul_u_ur_r_dr_d_dl = StaticTiledMapTile(brick[0][10])
    val brickBase_ul_ur_r_dr_d_dl_l = StaticTiledMapTile(brick[0][11])
    val brickBase_ul_u_ur_dr_d_dl_l = StaticTiledMapTile(brick[1][11])
    val brickBase_ul_u_ur_r_dr_dl_l = StaticTiledMapTile(brick[1][10])
    val brickBase_ul_u_ur = StaticTiledMapTile(brick[2][0])
    val brickBase_ur_r_dr = StaticTiledMapTile(brick[2][1])
    val brickBase_dr_d_dl = StaticTiledMapTile(brick[3][1])
    val brickBase_ul_dl_l = StaticTiledMapTile(brick[3][0])
    val brickBase_ul_u_ur_dl = StaticTiledMapTile(brick[2][2])
    val brickBase_ul_ur_r_dr = StaticTiledMapTile(brick[2][3])
    val brickBase_ur_dr_d_dl = StaticTiledMapTile(brick[3][3])
    val brickBase_ul_dr_dl_l = StaticTiledMapTile(brick[3][2])
    val brickBase_ul_u_ur_dr = StaticTiledMapTile(brick[2][4])
    val brickBase_ur_r_dr_dl = StaticTiledMapTile(brick[2][5])
    val brickBase_ul_dr_d_dl = StaticTiledMapTile(brick[3][5])
    val brickBase_ul_ur_dl_l = StaticTiledMapTile(brick[3][4])
    val brickBase_ul_u_ur_dr_dl = StaticTiledMapTile(brick[2][6])
    val brickBase_ul_ur_r_dr_dl = StaticTiledMapTile(brick[2][7])
    val brickBase_ul_ur_dr_d_dl = StaticTiledMapTile(brick[3][7])
    val brickBase_ul_ur_dr_dl_l = StaticTiledMapTile(brick[3][6])
    val brickBase_ul_u_ur_dr_d_dl = StaticTiledMapTile(brick[2][8])
    val brickBase_ul_ur_r_dr_dl_l = StaticTiledMapTile(brick[3][8])
    val brickBase_ul_dr = StaticTiledMapTile(brick[2][9])
    val brickBase_ur_dl = StaticTiledMapTile(brick[3][9])
    val brickBase_ul_ur_dr_dl = StaticTiledMapTile(brick[2][10])
    val brickBase_ul_u_ur_r_dr_d_dl_l = StaticTiledMapTile(brick[3][10])
    val brickBase_none = StaticTiledMapTile(brick[2][11])

    val brickWall_l_m_r = StaticTiledMapTile(brick[4][0])
    val brickWall_l_m = StaticTiledMapTile(brick[4][1])
    val brickWall_m = StaticTiledMapTile(brick[4][2])
    val brickWall_m_r = StaticTiledMapTile(brick[4][3])

    val brickHole_l_m_r = StaticTiledMapTile(brick[4][4])
    val brickHole_l_m = StaticTiledMapTile(brick[4][5])
    val brickHole_m = StaticTiledMapTile(brick[4][6])
    val brickHole_m_r = StaticTiledMapTile(brick[4][7])

    // metal

    val metal = TextureRegion(assetManager.get<Texture>("graphics/blocks/metal.png")).split(32, 32)

    val metalBase_ul = StaticTiledMapTile(metal[0][0])
    val metalBase_ur = StaticTiledMapTile(metal[0][1])
    val metalBase_dr = StaticTiledMapTile(metal[1][1])
    val metalBase_dl = StaticTiledMapTile(metal[1][0])
    val metalBase_ul_ur = StaticTiledMapTile(metal[0][2])
    val metalBase_ur_dr = StaticTiledMapTile(metal[0][3])
    val metalBase_dr_dl = StaticTiledMapTile(metal[1][3])
    val metalBase_ul_dl = StaticTiledMapTile(metal[1][2])
    val metalBase_ul_ur_dr = StaticTiledMapTile(metal[0][4])
    val metalBase_ur_dr_dl = StaticTiledMapTile(metal[0][5])
    val metalBase_ul_dr_dl = StaticTiledMapTile(metal[1][5])
    val metalBase_ul_ur_dl = StaticTiledMapTile(metal[1][4])
    val metalBase_ul_u_ur_r_dr = StaticTiledMapTile(metal[0][6])
    val metalBase_ur_r_dr_d_dl = StaticTiledMapTile(metal[0][7])
    val metalBase_ul_dr_d_dl_l = StaticTiledMapTile(metal[1][7])
    val metalBase_ul_u_ur_dl_l = StaticTiledMapTile(metal[1][6])
    val metalBase_ul_u_ur_r_dr_dl = StaticTiledMapTile(metal[0][8])
    val metalBase_ul_ur_r_dr_d_dl = StaticTiledMapTile(metal[0][9])
    val metalBase_ul_ur_dr_d_dl_l = StaticTiledMapTile(metal[1][9])
    val metalBase_ul_u_ur_dr_dl_l = StaticTiledMapTile(metal[1][8])
    val metalBase_ul_u_ur_r_dr_d_dl = StaticTiledMapTile(metal[0][10])
    val metalBase_ul_ur_r_dr_d_dl_l = StaticTiledMapTile(metal[0][11])
    val metalBase_ul_u_ur_dr_d_dl_l = StaticTiledMapTile(metal[1][11])
    val metalBase_ul_u_ur_r_dr_dl_l = StaticTiledMapTile(metal[1][10])
    val metalBase_ul_u_ur = StaticTiledMapTile(metal[2][0])
    val metalBase_ur_r_dr = StaticTiledMapTile(metal[2][1])
    val metalBase_dr_d_dl = StaticTiledMapTile(metal[3][1])
    val metalBase_ul_dl_l = StaticTiledMapTile(metal[3][0])
    val metalBase_ul_u_ur_dl = StaticTiledMapTile(metal[2][2])
    val metalBase_ul_ur_r_dr = StaticTiledMapTile(metal[2][3])
    val metalBase_ur_dr_d_dl = StaticTiledMapTile(metal[3][3])
    val metalBase_ul_dr_dl_l = StaticTiledMapTile(metal[3][2])
    val metalBase_ul_u_ur_dr = StaticTiledMapTile(metal[2][4])
    val metalBase_ur_r_dr_dl = StaticTiledMapTile(metal[2][5])
    val metalBase_ul_dr_d_dl = StaticTiledMapTile(metal[3][5])
    val metalBase_ul_ur_dl_l = StaticTiledMapTile(metal[3][4])
    val metalBase_ul_u_ur_dr_dl = StaticTiledMapTile(metal[2][6])
    val metalBase_ul_ur_r_dr_dl = StaticTiledMapTile(metal[2][7])
    val metalBase_ul_ur_dr_d_dl = StaticTiledMapTile(metal[3][7])
    val metalBase_ul_ur_dr_dl_l = StaticTiledMapTile(metal[3][6])
    val metalBase_ul_u_ur_dr_d_dl = StaticTiledMapTile(metal[2][8])
    val metalBase_ul_ur_r_dr_dl_l = StaticTiledMapTile(metal[3][8])
    val metalBase_ul_dr = StaticTiledMapTile(metal[2][9])
    val metalBase_ur_dl = StaticTiledMapTile(metal[3][9])
    val metalBase_ul_ur_dr_dl = StaticTiledMapTile(metal[2][10])
    val metalBase_ul_u_ur_r_dr_d_dl_l = StaticTiledMapTile(metal[3][10])
    val metalBase_none = StaticTiledMapTile(metal[2][11])

    val metalWall_l_m_r = StaticTiledMapTile(metal[4][0])
    val metalWall_l_m = StaticTiledMapTile(metal[4][1])
    val metalWall_m = StaticTiledMapTile(metal[4][2])
    val metalWall_m_r = StaticTiledMapTile(metal[4][3])

    val metalHole_l_m_r = StaticTiledMapTile(metal[4][4])
    val metalHole_l_m = StaticTiledMapTile(metal[4][5])
    val metalHole_m = StaticTiledMapTile(metal[4][6])
    val metalHole_m_r = StaticTiledMapTile(metal[4][7])
}
